envi = {
  'log_lvl': 20,
  'threads': 16,
  'smtp_server': '',
  'smtp_usr': '',
  'smtp_pwd': '',
  'smtp_server2': '',
  'smtp_usr2': '',
  'smtp_pwd2': '',
  'slog_server': '',
  'slog_port': 514,
  'ftp_server': '',
  'ftp_port': 21,
  'ftp_usr': '',
  'ftp_pwd': '',
  'ftp_dir': '',
  'save_interval': 7,
  'db_host': 'localhost',
  'db_port': 3306,
  'db_usr': 'netmon',
  'db_pwd': 'netmon',
  'db_name': 'netmon',
  'db_char': 'utf8'
}
